---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meridio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meridio-{{ .Release.Namespace }}-configuration-cluster-role
rules:
- apiGroups: 
  - ""
  resources: 
  - configmaps
  verbs: 
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meridio-{{ .Release.Namespace }}-configuration-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: meridio
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: meridio-{{ .Release.Namespace }}-configuration-cluster-role
  apiGroup: rbac.authorization.k8s.io