---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "vlan-conf",
            "ips": [ "169.254.100.254/24", "fe80::beef/64" ],
            "interface": "vlan0"
          }]'
      labels:
        app: gateway
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm-201
      tolerations:
      - key: "gw"
        operator: "Exists"
      containers:
        - name: bird
          image: registry.nordix.org/cloud-native/nfe-bird2:poc-0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: [ "/usr/sbin/bird" ]
          args: ["-d", "-c", "/etc/bird/bird-gw.conf"]

