---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meridio-configuration
data:
  meridio.conf: |
    vips: [{{ template "meridio.vips" . }}]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meridio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meridio-configuration-role
rules:
- apiGroups: 
  - ""
  resources: 
  - configmaps
  verbs: 
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meridio-configuration-role-binding
subjects:
- kind: ServiceAccount
  name: meridio
roleRef:
  kind: Role
  name: meridio-configuration-role
  apiGroup: rbac.authorization.k8s.io