---
apiVersion: v1
kind: Service
metadata:
  name: ipam-service
spec:
  selector:
    app: ipam
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.ipamPort }}
      targetPort: {{ .Values.ipamTargetPort }}