---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
  labels:
    app: load-balancer
spec:
  selector:
    matchLabels:
      app: load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      serviceAccountName: meridio
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "load-balancer"
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl-init
          image: {{ .Values.registry }}/{{ .Values.organization }}/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv6.conf.all.forwarding=1 ; sysctl -w net.ipv4.conf.all.forwarding=1 ; sysctl -w net.ipv4.fib_multipath_hash_policy=1 ; sysctl -w net.ipv6.fib_multipath_hash_policy=1
      containers:
        - name: load-balancer
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.loadBalancer.image }}:{{ .Values.loadBalancer.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_CONFIG_MAP_NAME
              value: meridio-configuration
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_SERVICE_NAME
              value: {{ template "meridio.loadBalancer.networkServiceName" . }}
            - name: NSM_VIPS
              value: {{ template "meridio.vips" . }}
            - name: NSM_NSP_SERVICE
              value: nsp-service:{{ .Values.nsp.targetPort }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            privileged: true
        - name: nsc
          image: registry.nordix.org/cloud-native/nsm/cmd-nsc:latest
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: vlan://{{ template "meridio.vlan.networkServiceName" . }}/ext-vlan?forwarder=forwarder-vlan
            - name: NSM_DIAL_TIMEOUT
              value: "30s"
            - name: NSM_REQUEST_TIMEOUT
              value: "300s"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate