---
apiVersion: v1
kind: Service
metadata:
  name: nsp-service
spec:
  selector:
    app: nsp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.nsp.port }}
      targetPort: {{ .Values.nsp.targetPort }}