---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target
  labels:
    app: target
spec:
  selector:
    matchLabels:
      app: target
  replicas: 4
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
        - name: target
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.targetImage }}:{{ .Values.targetVersion }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: kernel://proxy/nsm
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate